import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientSide from "./components/sidebarClient";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function TravelLayout({
  // Nama bisa diubah agar lebih deskriptif
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen">
      <ClientSide /> {/* Sidebar */}
      <main className="flex-1 bg-gray-50 p-6">{children}</main>
    </div>
  );
}